language: scala
jdk: openjdk11
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4
  sonarcloud:
    organization: "maproulette"
    token:
      secure: "UBzm2ip/ebaI+WA3zEvzMZ81RYOqNOi+ZK4VM1TqLejwzGkfJkn0yjzxmrKw8Ik/eECKApTwzWw8F8nMB2DtwnnHt7FEe4kPRAIuwjDE9UQB6s1orfDvJrKJwfzuBlotbsR7HnkK6CzjGOB6RXIAyLpsmCjrIvmhflkXQ9Cjrlkv5RBCpUuqJAhicL3+GGNYMLB2hBt8i7Vwi33KhUJL6BfEj4hgpv8S31Vxnct6tBNVaRz6iHfkGhZIbR4Z8y/4D6PXuEfVaTFKAhyrylEZEkgCkzcGzGhtN0bXTJYTmoG2YPmI7Kr4Oz+HqKhRcIbie5hdidg+fs86UFePeJATW//fs1VRnJFZIyg5oNjCg45o+R3vf/F3grLRo9nuHzt2xnz5r5ztIo1Wvydl/eCCpitu2LuuTj12u+zeug0ViNnhvTq+oVpizRWaUn/q/AAKpoNkFMQoHerKfIFoX4akpdHZjsxdlsTI90z1r60Ayr4SRTbQXYrhmiBKgVpfu3hSdgWtd5N2h27E601ycKgW6LmsmSqnl5KrWLUHqBU/OkE5FWEfkXtG1rMYs3B2GKl3rlY1d8DmZND8UF9CtJMHwBXa6Ctdq3FfK9tcB/GvDzZB9rDEHF6LPLRKsMzrUXCDq3kUEcSh2Gbu/TSnmjvpmezaneoFQZ4yEsColiDenLo="
env:
  global:
  - PGPORT=5432
services:
  - postgresql
before_script:
- psql -c "create database mr_test;" -U postgres
- psql -c "CREATE USER osm WITH PASSWORD 'osm';" -U postgres
- psql -c "CREATE EXTENSION postgis;" -U postgres -d mr_test
- psql -c "CREATE EXTENSION hstore;" -U postgres -d mr_test
script:
- sbt clean scalafmtCheckAll compile test
