---
  - type: play\.api\.libs\.json\.jsvalue
    specAsParameter: []
    specAsProperty:
      type: string
  - type: play\.api\.libs\.json\.jsobject
    specAsParameter: []
    specAsProperty:
      type: object
