---
  - type: play\.api\.libs\.json\.jsvalue
    specAsParameter: []
    specAsProperty:
      type: object
      additionalProperties: true
  - type: play\.api\.libs\.json\.jsobject
    specAsParameter: []
    specAsProperty:
      type: object
      additionalProperties: true
